// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using StressData.Database;

namespace StressMigrationsSqlite.Migrations
{
    [DbContext(typeof(StressDbContext))]
    [Migration("20201126012439_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("StressData.Model.StressRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Azimuth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISO")
                        .HasColumnType("TEXT");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("POINTZ")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WsmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("WsmId");

                    b.HasIndex("Location");

                    b.HasIndex("Quality");

                    b.HasIndex("Regime");

                    b.HasIndex("Type");

                    b.ToTable("stressrecord");
                });
#pragma warning restore 612, 618
        }
    }
}
